### ISSUE TITLE
plug-in will not load on docker-homebridge, wrong path to dependency. 

### ISSUE THREAD

**Issue by traviswparker** [hbblebc/homebridge-bed-control#1]
Plug-in fails to load on docker-homebridge (HB 1.5.0) with 
```
[9/8/2022, 1:27:16 AM] ====================
[9/8/2022, 1:27:16 AM] ERROR LOADING PLUGIN homebridge-bed-control:
[9/8/2022, 1:27:16 AM] Error: Cannot find module 'hap-nodejs/dist/lib/definitions'
Require stack:
- /homebridge/node_modules/homebridge-bed-control/dist/bedAccessory.js
```
 The container runs HB with extra flags: `-P /var/lib/homebridge/node_modules --strict-plugin-resolution` so the correct path to hap-nodejs is `homebridge/node_modules/hap-nodejs`

Prepending `homebridge/node_modules/` in line 4 of bedAccessory.js allows the plug-in to run.

**Comment by DeeeeLAN** [comment]
Thanks, I was wondering if I was missing a dependency or something. Do you know how to make tslint happy in my dev area after changing the import?

**Comment by hbblebc** [comment]
Thanks, I was wondering if I was missing a dependency or something when I saw that. I added it as a local dependency instead of relying on the homebridge version, which should fix it.

**Comment by traviswparker** [comment]
That I’m not sure of. I just know what I had to change to get it working in docker. Maybe recreate the same path for the homebridge core modules? On Sep 7, 2022, at 22:26, DeeeeLAN ***@***.***> wrote:﻿
Thanks, I was wondering if I was missing a dependency or something. Do you know how to make tslint happy in my dev area after changing the import?

**Comment by hbblebc** [comment]
Thanks, I think it should be fixed now.
